#!/usr/bin/env bash
# Reads Terraform outputs for the given environment and writes .env.
# Manually-held secrets (anon key, JWT secret) are preserved from the
# existing .env so re-running the script does not wipe them.
#
# Usage:
#   ./scripts/sync-env.sh staging      # default
#   ./scripts/sync-env.sh production
set -euo pipefail

ENV="${1:-staging}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
INFRA_DIR="$REPO_ROOT/infra/envs/$ENV"
ENV_FILE="$REPO_ROOT/.env"
TEMP_FILE="$(mktemp)"

trap 'rm -f "$TEMP_FILE"' EXIT

if [[ "$ENV" != "staging" && "$ENV" != "production" ]]; then
  echo "error: environment must be 'staging' or 'production'" >&2
  exit 1
fi

if ! command -v terraform &>/dev/null; then
  echo "error: terraform not found in PATH — install it first" >&2
  exit 1
fi

if [[ ! -d "$INFRA_DIR" ]]; then
  echo "error: $INFRA_DIR does not exist" >&2
  exit 1
fi

echo "Reading Terraform outputs for $ENV..."
cd "$INFRA_DIR"

if ! TF_OUTPUT=$(terraform output -json 2>/dev/null); then
  echo "error: terraform output failed — run 'terraform apply' for $ENV first" >&2
  exit 1
fi

# Parse a single key from the JSON output.
# Prefers jq; falls back to Python 3 (both are common on dev machines).
tf_value() {
  local key="$1"
  if command -v jq &>/dev/null; then
    echo "$TF_OUTPUT" | jq -r ".${key}.value // empty"
  else
    python3 - "$TF_OUTPUT" "$key" << 'PYEOF'
import json, sys
data = json.loads(sys.argv[1])
print(data.get(sys.argv[2], {}).get("value", ""))
PYEOF
  fi
}

TUS_SERVER_URL=$(tf_value "tus_server_url")
SUPABASE_API_URL=$(tf_value "supabase_api_url")

# Read a value from the existing .env, so we don't overwrite secrets
# the user already filled in.
existing_value() {
  local key="$1"
  local default="${2:-}"
  if [[ -f "$ENV_FILE" ]]; then
    local val
    val=$(grep -m1 "^${key}=" "$ENV_FILE" 2>/dev/null | cut -d'=' -f2- || true)
    echo "${val:-$default}"
  else
    echo "$default"
  fi
}

EXISTING_APP_ENV=$(existing_value "APP_ENV" "development")
EXISTING_ANON_KEY=$(existing_value "NEXT_PUBLIC_SUPABASE_ANON_KEY" "your-supabase-anon-key")
EXISTING_JWT_SECRET=$(existing_value "SUPABASE_JWT_SECRET" "your-supabase-jwt-secret")

cat > "$TEMP_FILE" << EOF
# Generated by scripts/sync-env.sh — env: $ENV — $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Re-run after terraform apply to pick up infra changes.
# NEXT_PUBLIC_SUPABASE_ANON_KEY and SUPABASE_JWT_SECRET are NOT managed by
# Terraform — set them once from the Supabase dashboard (Settings → API).

APP_ENV=${EXISTING_APP_ENV}

# ── Supabase ──────────────────────────────────────────────────────────────────
# URL is derived from the Terraform-managed project ref.
# ANON_KEY and JWT_SECRET are read from the Supabase dashboard and preserved here.
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${EXISTING_ANON_KEY}
SUPABASE_JWT_SECRET=${EXISTING_JWT_SECRET}

# ── Tus server ────────────────────────────────────────────────────────────────
# Value comes from terraform output tus_server_url.
NEXT_PUBLIC_TUS_SERVER_URL=${TUS_SERVER_URL}
EOF

mv "$TEMP_FILE" "$ENV_FILE"
echo "Written to $ENV_FILE"

# Warn about any placeholders that still need filling in
if grep -q "your-" "$ENV_FILE"; then
  echo ""
  echo "Warning: placeholder values remain — fill these in before starting the server:"
  grep "your-" "$ENV_FILE" | sed 's/^/  /'
fi
